researchproject/researchproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^wiki/', include('wikiserver.urls')),
    url(r'^admin/', admin.site.urls),
]

researchproject/wikiserver/urls.py
from django.conf.urls import url

from . import views


app_name = 'wikiserver'
urlpatterns = [
    # ex: /wiki/
    url(r'^$', views.IndexView, name='index'),

    # ex: /wiki/user/join/
    url(r'^user/join/$', views.UserJoinView, name='user-join'),
    # ex: /wiki/user/login/
    url(r'^user/login/$', views.UserLogInView, name='user-login'),
    # ex: /wiki/user/logout/
    url(r'^user/logout/$', views.UserLogOut, name='user-logout'),

    # ex: /wiki/page/create/
    url(r'^page/create/$', views.PageCreate, name='page-create'),
    # ex: /wiki/page/1/
    url(r'^page/(?P<pageid>[0-9]+)/$', views.PageView, name='page-view'),
    # ex: /wiki/page/list/1/
    url(r'^page/list/(?P<chapter>[0-9]+)/$', views.PageList, name='page-list'),
    # ex: /wiki/page/1/edit
    url(r'^page/(?P<pageid>[0-9]+)/edit/$', views.PageEdit, name='page-edit'),
    # ex: /wiki/page/1/version/list/1
    url(r'^page/(?P<pageid>[0-9]+)/version/list/(?P<chapter>[0-9]+)/$', views.PageVersionList, name='page-version-list'),
    # ex: /wiki/page/1/version/1
    url(r'^page/(?P<pageid>[0-9]+)/version/(?P<version>[0-9]+)/$', views.PageVersionView, name='page-version-view'),

]

researchproject/wikiserver/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Page(models.Model):
    """
    contains current page info
    """
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    title = models.CharField(max_length=300, default='title unavailable', null=False, blank=True)
    content = models.TextField(max_length=40000, default='content unavailable', null=False, blank=True)
    date_edited = models.DateTimeField(auto_now=True, null=True)


class Page_Version(models.Model):
    """
    contains previous page info for version control
    """
    page = models.ForeignKey(Page, on_delete=models.CASCADE, null=True)
    version = models.IntegerField(default=1, null=True)
    title = models.CharField(max_length=300, default='title unavailable', null=False, blank=True)
    content = models.TextField(max_length=40000, default='content unavailable', null=False, blank=True)
    date_edited = models.DateTimeField(auto_now_add=True, null=True)

researchproject/wikiserver/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout, login
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required

from .util import CreateUserValidation, FormValidation, PageUtil
from .models import Page, Page_Version
import requests

from difflib import HtmlDiff
import diff_match_patch as dmp_module


def IndexView(request):
    """
    home page
    """

    context = {
        'username': request.user.username,
        'recentPages': Page.objects.order_by('-date_created')[:5]
    }

    return render(request, 'wikiserver/index.html', context)


def UserJoinView(request):
    """
    user account creation form
    """

    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('wikiserver:index', args=()))

    context = {
        'username': None,
        'next': request.GET.get('next', None),
        'errorMessage': None,
        'formUsername': ''
    }

    if request.method == 'POST':
        # validate form
        fields = ['username', 'password', 'verifyPassword']
        if not FormValidation.formContainsAll(request.POST, fields):
            context['errorMessage'] = 'Invalid form, did not contain username, password, and/or verifyPassword'
            return render(request, 'wikiserver/user-join.html', context, status=400)

        uInput = context['formUsername'] = str(request.POST['username'])
        pInput = str(request.POST['password'])
        vpInput = str(request.POST['verifyPassword'])

        # validate, username is unique and alpha-numeric
        validation = CreateUserValidation.isValidUsername(uInput)
        if not validation['isValid']:
            context['errorMessage'] = validation['message']
            context['formUsername'] = ''
            return render(request, 'wikiserver/user-join.html', context, status=400)

        # validate, password is at least 4 characters
        validation = CreateUserValidation.isValidPassword(pInput)
        if not validation['isValid']:
            context['errorMessage'] = validation['message']
            return render(request, 'wikiserver/user-join.html', context, status=400)

        # validate, passwords match
        if pInput != vpInput:
            context['errorMessage'] = 'Passwords do not match'
            return render(request, 'wikiserver/user-join.html', context, status=400)

        # create user
        user = User.objects.create_user(uInput, None, pInput)
        user.save()

        # login user
        login(request, user)

        # redirect
        if context['next'] is None:
            context['next'] = reverse('wikiserver:index', args=())

        return HttpResponseRedirect(context['next'])

    else:
        return render(request, 'wikiserver/user-join.html', context)


def UserLogInView(request):
    """
    user log in form
    """

    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('wikiserver:index', args=()))

    context = {
        'username': None,
        'next': request.GET.get('next', None),
        'errorMessage': None
    }

    if request.method == 'POST':
        # validate form
        fields = ['username', 'password']
        if not FormValidation.formContainsAll(request.POST, fields):
            context['errorMessage'] = 'Invalid form, did not contain username and/or password'
            return render(request, 'wikiserver/user-login.html', context, status=400)

        uInput = str(request.POST['username'])
        pInput = str(request.POST['password'])

        # authenticate user
        user = authenticate(username=uInput, password=pInput)
        if user is None:
            context['errorMessage'] = 'Invalid login, please try again'
            return render(request, 'wikiserver/user-login.html', context, status=400)
        else:
            login(request, user)
            if context['next'] is None:
                context['next'] = reverse('wikiserver:index', args=())

            return HttpResponseRedirect(context['next'])

    else:
        return render(request, 'wikiserver/user-login.html', context)


def UserLogOut(request):
    """
    logs out user
    """

    logout(request)
    return HttpResponseRedirect(reverse('wikiserver:index', args=()))


@login_required
def PageCreate(request):
    """
    page creation form
    """

    context = {
        'username': request.user.username,
        'creatingNewPage': True,
        'formTitle': '',
        'formContent': '',
        'errorMessage': None,
        'disable': False
    }

    if request.method == 'POST':
        # validate form
        fields = ['title', 'content']
        if not FormValidation.formContainsAll(request.POST, fields):
            context['errorMessage'] = 'Invalid form, did not contain title and/or content'
            return render(request, 'wikiserver/page-editor.html', context, status=400)

        tInput = context['formTitle'] = request.POST['title']
        cInput = context['formContent'] = request.POST['content']

        # validate title
        if len(tInput) < 1:
            context['errorMessage'] = "Please provide a title"
            return render(request, 'wikiserver/page-editor.html', context, status=400)

        # validate content
        if len(cInput) < 1:
            context['errorMessage'] = "Page must have content"
            return render(request, 'wikiserver/page-editor.html', context, status=400)

        page = Page(owner=request.user, title=tInput, content=cInput)
        page.save()

        return HttpResponseRedirect(reverse('wikiserver:page-view', args=(page.id,)))

    else:
        return render(request, 'wikiserver/page-editor.html', context)


def PageView(request, pageid):
    """
    view a page
    """

    context = {
        'username': request.user.username,
        'canEdit': False,
        'page': {},
        'markdownAvailable': True,
        'diff': '',
        'original': '',
    }

    try:
        context['page'] = Page.objects.get(id=pageid)
    except Page.DoesNotExist:
        raise Http404("Page does not exist")

    if context['page'].owner.username == context['username']:
        context['canEdit'] = True

    try:
        headers = {'Content-Type': 'text/plain'}
        data = context['original'] = context['page'].content
        md = requests.post('https://api.github.com/markdown/raw', headers=headers, data=data)
        if md.status_code < 300:
            context['page'].content = md.text
        else:
            context['markdownAvailable'] = False
            print('%d error: %s' % (md.status_code, md.text,))
    except requests.exceptions.RequestException as e:
        context['markdownAvailable'] = False
        print('error: %s' % (e,))

    # get diff if available
    latestVersion = PageUtil.getLatestVersion(pageid)
    if latestVersion is not None:
        # get diff
        dmp = dmp_module.diff_match_patch()
        diff = dmp.diff_main(latestVersion.content, context['original'])
        dmp.diff_cleanupSemantic(diff)
        context['diff'] = dmp.diff_prettyHtml(diff)

    return render(request, 'wikiserver/page-view.html', context)


def PageList(request, chapter):
    """
    view a list of all pages, 10 per chapter
    chapter is equivalent to list-page
    """

    context = {
        'username': request.user.username,
        'pagesToDisplay': [],
        'chapterLinks': []
    }

    # get all pages
    allPages = Page.objects.order_by('-date_created')
    numOfPages = len(allPages)

    # number of pages to display per chapter (list-page)
    chapterSize = 5

    # get the total number of chapters
    numOfChapters = numOfPages / chapterSize
    if numOfPages % chapterSize != 0:
        numOfChapters += 1

    # error check current chapter
    chapter = int(chapter)
    if chapter < 1:
        return HttpResponseRedirect(reverse('wikiserver:page-list', args=(1,)))
    elif chapter > numOfChapters:
        return HttpResponseRedirect(reverse('wikiserver:page-list', args=(numOfChapters,)))

    # get pages to display
    start = (chapter - 1) * chapterSize
    context['pagesToDisplay'] = allPages[start : start + chapterSize]

    # if has previous
    if chapter > 1:
        context['chapterLinks'].append({'link': chapter - 1, 'text': 'prev'})

    # get the full list of chapters
    for i in range(1, numOfChapters + 1):
        context['chapterLinks'].append({'link': i, 'text': i})

    # if has next
    if chapter < numOfChapters:
        context['chapterLinks'].append({'link': chapter + 1, 'text': 'next'})

    return render(request, 'wikiserver/page-list.html', context)


@login_required
def PageEdit(request, pageid):
    """
    page edit form
    """

    context = {
        'username': request.user.username,
        'creatingNewPage': False,
        'pid': pageid,
        'formTitle': '',
        'formContent': '',
        'errorMessage': None,
        'disable': False
    }

    try:
        page = Page.objects.get(id=pageid)
        if (page.owner != request.user):
            context['formTitle'] = page.title
            context['formContent'] = page.content
            context['errorMessage'] = 'Only the author can edit this page.'
            context['disable'] = True
            return render(request, 'wikiserver/page-editor.html', context, status=403)
    except Page.DoesNotExist:
        raise Http404("Page does not exist")

    if request.method == 'POST':
        # validate form
        fields = ['title', 'content']
        if not FormValidation.formContainsAll(request.POST, fields):
            context['errorMessage'] = 'Invalid form, did not contain title and/or content'

researchproject/templates/wikiserver/base.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, minimum-scale=1, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'wikiserver/css/main.css' %}">
  <script src="{% static 'libraries/jquery-3.3.1.min.js' %}"></script>
  <title>Wiki Server</title>
</head>
<body>
  <div class="header-bar">
    <div class="title"><a href="{% url 'wikiserver:index' %}">Wiki Server</a></div>
    <div class="btns">
      {% if username %}
      <div class="btn">
        <a href="{% url 'wikiserver:user-logout' %}">log out</a>
      </div>
      {% else %}
      <div class="btn">
        <a href="{% url 'wikiserver:user-join' %}">sign up</a>
      </div>
      <div class="btn">
        <a href="{% url 'wikiserver:user-login' %}">log in</a>
      </div>
      {% endif %}
    </div>
  </div>
  <div class="content">
    {% block 'body' %}
    {% endblock %}
  </div>
</body>
</html>

researchproject/templates/wikiserver/index.html
{% extends 'wikiserver/base.html' %}
{% block 'body' %}

{% if username %}
  <h1>Welcome {{username}}</h1>
{% else %}
  <h2>Welcome. Please <a href="{% url 'wikiserver:user-login' %}">log in</a> or <a href="{% url 'wikiserver:user-join' %}">create an account</a>.</h2>
{% endif %}

{% if recentPages %}
  <h3>Recently Created Pages</h3>
  <ul>
  {% for p in recentPages %}
    <li style="margin-bottom:10px;"><a href="{% url 'wikiserver:page-view' pageid=p.id %}">{{ p.title }}</a> by {{ p.owner.username }}</li>
  {% endfor %}
  </ul>
  <p><a href="{% url 'wikiserver:page-list' chapter=1 %}">View all pages</a></p>
{% endif %}

{% if username %}
  <p><a href="{% url 'wikiserver:page-create' %}">Create a page</a></p>
{% endif %}

{% endblock %}

researchproject/templates/wikiserver/page-create.html
{% extends 'wikiserver/base.html' %}
{% block 'body' %}
<button id="editor-btn">Edit</button>
<button id="preview-btn">Preview</button>

<div id="editor">
  <form action="{% url 'wikiserver:page-create' %}" method="post">
    {% csrf_token %}

    <input type="text" name="title" id="title" value="{{formTitle}}"/>
    <label for="title">Title</label><br/>

    <textarea style="width:400px;height:150px;" name="content" id="content">{{formContent}}</textarea>
    <label for="content">Content</label><br/>

    <p id="error">
      {% if errorMessage %}
      <strong>{{errorMessage}}</strong>
      {% endif %}
    </p>

    <input type="submit" value="Create"/>
  </form>
</div>

<div id="preview" style="display:none;">
</div>

<script>
  $(document).ready(function() {
    $("#editor-btn").click(function() {
      document.getElementById("editor").style.display = "block";
      document.getElementById("preview").style.display = "none";
    });

    $("#preview-btn").click(function() {
      $.ajax({
        type: "POST",
        dataType: "html",
        processData: false,
        url: "https://api.github.com/markdown/raw",
        data: document.getElementById("content").value,
        contentType: "text/plain",
        success: function(data){
          $("#preview").html("<h1>" + document.getElementById("title").value + "</h1>")
          $("#preview").append(data);
          document.getElementById("editor").style.display = "none";
          document.getElementById("preview").style.display = "block";
        },
        error: function(jqXHR, textStatus, error){
          $("#error").html("<strong>Something went wrong with the preview.</strong>");
          console.log(jqXHR, textStatus, error);
        }
      });
    });
  });
</script>
{% endblock %}

researchproject/templates/wikiserver/page-editor.html
{% extends 'wikiserver/base.html' %}
{% block 'body' %}
{% if creatingNewPage %}
<h1>New Page</h1>
{% else %}
<h1>Edit Page</h1>
{% endif %}

<button id="editor-btn">Edit</button>
<button id="preview-btn">Preview</button>

<div id="editor">
  <form action={% if creatingNewPage %}"{% url 'wikiserver:page-create' %}"{% else %}"{% url 'wikiserver:page-edit' pageid=pid %}"{% endif %} method="post">
    {% csrf_token %}

    <input type="text" name="title" id="title" value="{{formTitle}}" {% if disable %}disabled{% endif %}/>
    <label for="title">Title</label><br/>

    <textarea style="width:400px;height:150px;" name="content" id="content" {% if disable %}disabled{% endif %}>{{formContent}}</textarea>
    <label for="content">Content</label><br/>

    <input type="submit" value={% if creatingNewPage %}"Create"{% else %}"Save"{% endif %} {% if disable %}disabled{% endif %}/>
  </form>
</div>

<div id="preview" style="display:none;">
</div>

<p id="error">
  {% if errorMessage %}
  <strong>{{errorMessage}}</strong>
  {% endif %}
</p>

<script>
  $(document).ready(function() {
    $("#editor-btn").click(function() {
      document.getElementById("editor").style.display = "block";
      document.getElementById("preview").style.display = "none";
    });

    $("#preview-btn").click(function() {
      $.ajax({
        type: "POST",
        dataType: "html",
        processData: false,
        url: "https://api.github.com/markdown/raw",
        data: document.getElementById("content").value,
        contentType: "text/plain",
        success: function(data){
          $("#preview").html("<h1>" + document.getElementById("title").value + "</h1>")
          $("#preview").append(data);
          document.getElementById("editor").style.display = "none";
          document.getElementById("preview").style.display = "block";
        },
        error: function(jqXHR, textStatus, error){
          $("#error").html("<strong>Something went wrong with the preview.</strong>");
          console.log(jqXHR, textStatus, error);
        }
      });
    });
  });
</script>
{% endblock %}

researchproject/templates/wikiserver/page-list.html
{% extends 'wikiserver/base.html' %}
{% block 'body' %}

<h3>All Pages</h3>
<ul>
{% for p in pagesToDisplay %}
  <li style="margin-bottom:10px;"><a href="{% url 'wikiserver:page-view' p.id %}">{{p.title}}</a> by {{p.owner.username}}</li>
{% endfor %}
</ul>

<p style="text-align:center;">
  {% for c in chapterLinks %}
    <a href="{% url 'wikiserver:page-list' c.link %}">{{c.text}}</a>
  {% endfor %}
</p>

{% endblock %}

researchproject/templates/wikiserver/page-version-list.html
{% extends 'wikiserver/base.html' %}
{% block 'body' %}

<h3>Previous Versions of This Page</h3>
<a href="{% url 'wikiserver:page-view' pageid=pid %}">back to current version</a>
<ul>
{% for v in versionsToDisplay %}
  <li style="margin-bottom:10px;"><a href="{% url 'wikiserver:page-version-view' pageid=v.page_id version=v.version %}">{{v.version}}: {{v.date_edited}}</a></li>
{% endfor %}
</ul>

<p style="text-align:center;">
  {% if prev %}<a href="{% url 'wikiserver:page-version-list' pageid=pid chapter=prev %}">Newer</a>{% endif %}
  {% if next %}<a href="{% url 'wikiserver:page-version-list' pageid=pid chapter=next %}">Older</a>{% endif %}
</p>

{% endblock %}

researchproject/templates/wikiserver/page-version-view.html
{% extends 'wikiserver/base.html' %}
{% block 'body' %}

<h3>View Version</h3>
<a href="{% url 'wikiserver:page-version-list' pageid=pid chapter=1 %}">back to version list</a>
<br>
<br>
<h4>Version {{pageVersion.version}}<h4>
<div id="content">
<p>{{pageVersion.content | safe}}</p>
</div>
<div id="diff" style="display:none;">
<p>{{diff | safe}}</p>
</div>
<br>
<br>

{% if diff %}
<a id="diff-btn" href="javascript:void(0)">Diff</a>
{% endif %}

<script>
  $(document).ready(function() {
    $("#diff-btn").click(function() {
      if (document.getElementById("diff").style.display === "block") {
        document.getElementById("diff").style.display = "none";
        document.getElementById("content").style.display = "block";
      }
      else {
        document.getElementById("diff").style.display = "block";
        document.getElementById("content").style.display = "none";
      }
    });
  });
</script>

{% endblock %}

researchproject/templates/wikiserver/page-versions.html
{% extends 'wikiserver/base.html' %}
{% block 'body' %}

<h3>Previous Versions of This Page</h3>
<ul>
{% for v in versionsToDisplay %}
  <li style="margin-bottom:10px;"><a href="{% url 'wikiserver:page-version-view' pageid=v.page_id versionid=v.version %}">{{v.version}}: {{v.date_edited}}</a></li>
{% endfor %}
</ul>

<p style="text-align:center;">
  {% if prev %}<a href="{% url 'wikiserver:page-version-list' pageid=pid chapter=prev %}">Newer</a>{% endif %}
  {% if next %}<a href="{% url 'wikiserver:page-version-list' pageid=pid chapter=next %}">Older</a>{% endif %}
</p>

{% endblock %}

researchproject/templates/wikiserver/page-view.html
{% extends 'wikiserver/base.html' %}
{% block 'body' %}

<h2>{{page.title}}</h2>
<h5>by {{page.owner.username}}</h5>

<div id="content">
<p>{{page.content | safe}}</p>
</div>
<div id="diff" style="display:none;">
<p>{{diff | safe}}</p>
</div>

<br>
<br>
<div>
  {% if not markdownAvailable %}
  <p>Something went wrong with the Markdown converter. Please try refreshing the page.</p>
  {% endif %}
</div>

{% if canEdit %}
<a href="{% url 'wikiserver:page-edit' pageid=page.id %}">Edit</a>&nbsp;&nbsp;|&nbsp;&nbsp;
<a id="diff-btn" href="javascript:void(0)">Diff</a>&nbsp;&nbsp;|&nbsp;&nbsp;
<a href="{% url 'wikiserver:page-version-list' pageid=page.id chapter=1 %}">Previous Versions</a>
{% endif %}

<script>
  $(document).ready(function() {
    $("#diff-btn").click(function() {
      if (document.getElementById("diff").style.display === "block") {
        document.getElementById("diff").style.display = "none";
        document.getElementById("content").style.display = "block";
      }
      else {
        document.getElementById("diff").style.display = "block";
        document.getElementById("content").style.display = "none";
      }
    });
  });
</script>

{% endblock %}

researchproject/templates/wikiserver/post-create.html
{% extends 'wikiserver/base.html' %}
{% block 'body' %}
<form action="{% url 'wikiserver:post-create' %}" method="post">{% csrf_token %}
  <input type="text" name="title" id="title"/>
  <label for="title">Title</label><br/>

  <textarea style="width:400px;height:150px;" name="content" id="content">{{content}}</textarea>
  <label for="content">Content</label><br/>

  {% if errorMessage %}
  <p><strong>{{errorMessage}}</strong></p>
  {% endif %}

  <input type="submit" value="Post"/>
</form>
{% endblock %}

researchproject/templates/wikiserver/user-join.html
{% extends 'wikiserver/base.html' %}
{% block 'body' %}

<h1>Create An Account</h1>

<form action="{% url 'wikiserver:user-join' %}{% if next %}?next={{next}}{% endif %}" method="post">{% csrf_token %}
  <input type="text" name="username" id="username" value="{{formUsername}}"/>
  <label for="username">Username</label><br/>

  <input type="password" name="password" id="password"/>
  <label for="password">Password</label><br/>

  <input type="password" name="verifyPassword" id="verifyPassword"/>
  <label for="verifyPassword">Verify Password</label><br/>

  {% if errorMessage %}
  <p><strong>{{errorMessage}}</strong></p>
  {% endif %}

  <input type="submit" value="Create Account" />
</form>

{% endblock %}

researchproject/templates/wikiserver/user-login.html
{% extends 'wikiserver/base.html' %}
{% block 'body' %}

<h1>Log In</h1>

<form action="{% url 'wikiserver:user-login' %}{% if next %}?next={{next}}{% endif %}" method="post">
  {% csrf_token %}

  <input type="text" name="username" id="username"/>
  <label for="username">Username</label><br/>

  <input type="password" name="password" id="password"/>
  <label for="password">Password</label><br/>

  {% if errorMessage %}
  <p><strong>{{errorMessage}}</strong></p>
  {% endif %}

  <input type="submit" value="Log In"/>

  <p>New? <a href="{% url 'wikiserver:user-join' %}{% if next %}?next={{next}}{% endif %}">Create an account</a>
</form>

{% endblock %}

researchproject/templates/wikiserver/user-signup.html
{% extends 'wikiserver/base.html' %}
{% block 'body' %}

<h1>Create An Account</h1>

<form action="{% url 'wikiserver:user-signup' %}{% if n %}?next={{n}}{% endif %}" method="post">{% csrf_token %}
  <input type="text" name="username" id="username" value="{{username}}"/>
  <label for="username">Username</label><br/>

  <input type="password" name="password" id="password"/>
  <label for="password">Password</label><br/>

  <input type="password" name="verifyPassword" id="verifyPassword"/>
  <label for="verifyPassword">Verify Password</label><br/>

  {% if errorMessage %}
  <p><strong>{{errorMessage}}</strong></p>
  {% endif %}

  <input type="submit" value="Create Account" />
</form>

{% endblock %}